version: '3'

services:
  tests:
    build: .
    image: trello-api-tests
    container_name: test-container
    environment:
      - CONFIG_FILE=/app/src/test/resources/config.properties
    volumes:
      - ./target/allure-results:/app/target/allure-results



