version: '3'

services:
  tests:
    build: .
    image: trello-api-tests
    container_name: test-container
    environment:
      key: $key
      token: $token
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./src/test/resources/config.properties:/app/src/test/resources/config.properties

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

