version: '3'

services:
  tests:
    build: .
    image: trello-api-tests
    container_name: test-container
    environment:
      key: $key
      token: $token
    volumes:
      - ./target/allure-results:/app/target/allure-results
      - ./src/test/resources/config.properties:/app/src/test/resources/config.properties



